apiVersion: v2
name: trackmyjobs
description: A Helm chart for Kubernetes
type: application
version: 1.0.0-SNAPSHOT
appVersion: 1.0.0-SNAPSHOT
dependencies:
  - name: keycloak
    version: 24.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: keycloak.enabled
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.3.5
    condition: postgresql.enabled
  - name: tmj-api
    repository: file://../../tmj-api/helm/tmj-api
    version: 1.0.0-SNAPSHOT
    condition: tmj-api.enabled
  - name: tmj-web
    repository: file://../../tmj-web/helm/tmj-web
    version: 1.0.0-SNAPSHOT
    condition: tmj-web.enabled
